# Generated by Django 3.2.7 on 2021-10-07 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_delete_chatroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demo',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
