# Generated by Django 3.2.7 on 2021-10-27 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('resolve', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('credit_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit', to='accounting.transactionuser')),
                ('debit_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit', to='accounting.transactionuser')),
            ],
        ),
        migrations.CreateModel(
            name='OrderTransactionTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], max_length=200)),
                ('from_user', models.CharField(choices=[('me', 'me'), ('da', 'delivery_agent'), ('c', 'customer')], max_length=200)),
                ('to_user', models.CharField(choices=[('me', 'me'), ('da', 'delivery_agent'), ('c', 'customer')], max_length=200)),
                ('resolve', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('from_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_status', to='order.orderstatus')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shop')),
                ('to_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_status', to='order.orderstatus')),
            ],
        ),
    ]
