# Generated by Django 3.2.7 on 2021-10-27 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='msg',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='shop_order_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.shoporderstatus'),
        ),
    ]
