# Generated by Django 4.0.4 on 2022-04-26 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='middle_name',
        ),
    ]
